//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppNetUserType
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string UserType { get; set; }
        public string DateCreate { get; set; }
        public string Expire { get; set; }
        public int LocationID { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string TaxID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> LocationSubID { get; set; }
    }
}
