//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Code { get; set; }
        public string UserID { get; set; }
    }
}
