//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSub
    {
        public int ID { get; set; }
        public int IDLocation { get; set; }
        public string Name { get; set; }
        public string LocationPrice { get; set; }
        public string Description { get; set; }
        public Nullable<byte> IsDel { get; set; }
        public Nullable<bool> Show { get; set; }
    }
}
