//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public long ID { get; set; }
        public long ProductID { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
        public Nullable<int> LocationID { get; set; }
    }
}
