//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCode
    {
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public bool CatID { get; set; }
        public int ScrollNumber { get; set; }
        public int ID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CatCode { get; set; }
    }
}
