//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public long ID { get; set; }
        public string ProductCode { get; set; }
        public string Image { get; set; }
        public string ImageLink { get; set; }
        public string Note { get; set; }
        public string ImageAddIn { get; set; }
        public string Component { get; set; }
    }
}
