//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionType
    {
        public string ProTypeName { get; set; }
        public string AddType { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public int ID { get; set; }
    }
}
